### ISSUE TITLE
Firmware documentation problem

### ISSUE THREAD

**Issue by koocotte** [sonocotta/attiny-flasher#1]
In file [attiny-flasher](https://github.com/sonocotta/attiny-flasher)/hardware/README.md file, section "Mode Switches";

Text said "When ON (...) TARGET MCU. When OFF it will allow to flash HOST MCU"; 

but in the ON column, there is "Flash HOST" and in the OFF one: "Flash TARGET"

**Comment by anabolyc** [comment]
Hi @koocotte. Thanks for the tip. You're right, it is misleading. I fixed it just now.
