### ISSUE TITLE
Flashing firmware result in "error" LED

### ISSUE THREAD

**Issue by koocotte** [sonocotta/attiny-flasher#2]
Hello.

I don't know if here is the best place to try to solve this sort of problem.

I tried to re-flash my attiny-flasher rev G to use 19200 bps to work with the arduino IDE.

As specified on firmware/README.md, I put all 3 switch 'OFF' and updated hardware/README.md with "#define BAUDRATE_IN 19200".
In platformio, the Build and Upload task where successfull.

But on reboot; there is no more draw on the screen and the "ERR" led is red.

Here are the Upload log (don't know if it's useful)

[attiny-upload.txt](https://github.com/sonocotta/attiny-flasher/files/11015535/attiny-upload.txt)

**Comment by anabolyc** [comment]
Hi @koocotte .
Quick health check: 
- please make sure your HW version is G
- which folder (project) you took for the repo?
- can you please make sure that version of the code is the latest

Just tried the same on my end, and first thing that I noticed, dependency graph should be much smaller
```
Dependency Graph
|-- Tiny4kOLED @ 1.5.4
|   |-- Wire @ 1.0
|-- SPI @ 1.0
|-- Wire @ 1.0
|-- SoftwareSerial @ 1.0
```

**Comment by koocotte** [comment]
Hello,

"ATTINY FLASHER
REV G" is written on the back of the board

Here is the repo i use:
```
seb@octarine:~/tmp/attiny-flasher/firmware/flasher/attiny-flasher$ git remote -v
origin  https://github.com/sonocotta/attiny-flasher/ (fetch)
origin  https://github.com/sonocotta/attiny-flasher/ (push)
seb@octarine:~/tmp/attiny-flasher/firmware/flasher/attiny-flasher$ git pull
Already up to date.
```
In Platformio (the ant-face tab), I use the file `attiny-flasher/firmware/flasher/attiny-flasher/platformio.ini` and the task `atmega328-tiny-rev-g/General/Upload`

I run vscode on Linux, I don't know if this can have any incidence on the dependency graph.

**Comment by anabolyc** [comment]
Hi @koocotte. I just noticed, that I did quite a few changes in the fork, rather than in this repo. I just committed "sync" changeset. It doesn't address your issue directly, but it will update your code to the version I'm using. 
Could you please pull the latest code and flash firmware once again. Please note if dependency graph will stay the same or become shorter.

**Comment by koocotte** [comment]
Hello,

I updated the repo and now, the dependency graph is the same as yours.

Good news: I reflashed the board with the updated code, and the ERR is gone and the splash screen is back!
